export const States = [
  { key: 0, text: "Alabama", value: "AL" },
  { key: 1, text: "Alaska", value: "AK" },
  { key: 2, text: "Arizona", value: "AZ" },
  { key: 3, text: "Arkansas", value: "AR" },
  { key: 4, text: "California", value: "CA" },
  { key: 5, text: "Colorado", value: "CO" },
  { key: 6, text: "Connecticut", value: "CT" },
  { key: 7, text: "Delaware", value: "DE" },
  { key: 8, text: "Florida", value: "FL" },
  { key: 9, text: "Georgia", value: "GA" },
  { key: 10, text: "Hawaii", value: "HI" },
  { key: 11, text: "Idaho", value: "ID" },
  { key: 12, text: "Illinois", value: "IL" },
  { key: 13, text: "Indiana", value: "IN" },
  { key: 14, text: "Iowa", value: "IA" },
  { key: 15, text: "Kansas", value: "KS" },
  { key: 16, text: "Kentucky", value: "KY" },
  { key: 17, text: "Louisiana", value: "LA" },
  { key: 18, text: "Maine", value: "ME" },
  { key: 19, text: "Maryland", value: "MD" },
  { key: 20, text: "Massachusetts", value: "MA" },
  { key: 21, text: "Michigan", value: "MI" },
  { key: 22, text: "Minnesota", value: "MN" },
  { key: 23, text: "Mississippi", value: "MS" },
  { key: 24, text: "Missouri", value: "MO" },
  { key: 25, text: "Montana", value: "MT" },
  { key: 26, text: "Nebraska", value: "NE" },
  { key: 27, text: "Nevada", value: "NV" },
  { key: 28, text: "New Hampshire", value: "NH" },
  { key: 29, text: "New Jersey", value: "NJ" },
  { key: 30, text: "New Mexico", value: "NM" },
  { key: 31, text: "New York", value: "NY" },
  { key: 32, text: "North Carolina", value: "NC" },
  { key: 33, text: "North Dakota", value: "ND" },
  { key: 34, text: "Ohio", value: "OH" },
  { key: 35, text: "Oklahoma", value: "OK" },
  { key: 36, text: "Oregon", value: "OR" },
  { key: 37, text: "Pennsylvania", value: "PA" },
  { key: 38, text: "Rhode Island", value: "RI" },
  { key: 39, text: "South Carolina", value: "SC" },
  { key: 40, text: "Dakota", value: "SD" },
  { key: 41, text: "Tennessee", value: "TN" },
  { key: 42, text: "Texas", value: "TX" },
  { key: 43, text: "Utah", value: "UT" },
  { key: 44, text: "Vermont", value: "VT" },
  { key: 45, text: "Virginia", value: "VA" },
  { key: 46, text: "Washington", value: "WA" },
  { key: 47, text: "West Virginia", value: "WV" },
  { key: 48, text: "Wisconsin", value: "WI" },
  { key: 49, text: "Wyoming", value: "WY" },
];
